### ISSUE TITLE
Microsoft Accounts

### ISSUE THREAD

**Issue by PinkGoosik** [PlanetTeamSpeakk/DevLogin#1]
Hello I have been using this mod for a while but after account migration, it stopped working, if you could add support for Microsoft accounts that would be awesome

**Comment by PlanetTeamSpeakk** [comment]
I'll have a look and see if I can figure out how to log in with Microsoft accounts.

**Comment by PlanetTeamSpeakk** [comment]
Feature has been added.

**Comment by PinkGoosik** [comment]
Pog
