### ISSUE TITLE
Username doesn't work

### ISSUE THREAD

**Issue by Xyndra** [PlanetTeamSpeakk/DevLogin#19]
Usernames don't acutally work and it doesn't look like there was any code for them made either. Please either fix or remove from descriptions.

**Comment by PlanetTeamSpeakk** [comment]
I don't think I mention usernames anywhere. They used to be a thing when you could login with a Mojang account, but have since been removed. Not sure what you're referring to here, though.

**Comment by Xyndra** [comment]
I meant in game usernames
![image](https://github.com/user-attachments/assets/6c9a3b56-df08-4b17-9058-c9fdb9a524bf)

**Comment by Xyndra** [comment]
works rn tho
