### ISSUE TITLE
Unknown command-line option '--msa' on IntelliJ

### ISSUE THREAD

**Issue by mageowl** [PlanetTeamSpeakk/DevLogin#9]
When trying to launch Minecraft using this as a dependency on IntelliJ it gives the error "Unknown command-line option '--msa'." I've tried using --mimick and --msa-nostore as well.

**Comment by Diogo-Almeida3** [comment]
Hey.
Instead of using the gradle to run the client use the "MinecraftClient" and then add "--msa-nostore" to cli arguments.

![820c4182d934025c2232430a21d4fa48](https://user-images.githubusercontent.com/46142686/209726254-a1b41880-d90b-4fe4-a8e2-4d102126e37c.png)

**Comment by PlanetTeamSpeakk** [comment]
Yeah, I'm guessing you added the arguments wrongly. They have to be added as program arguments or they'll be misinterpreted and won't work/cause issues.

**Comment by mageowl** [comment]
Tried that, it says `Completely ignored arguments: [--msa / --msa-nostore]` instead of erroring. It launches, but doesn't work. (I tried with nostore too.)

![Screenshot 2022-12-28 at 7 53 15 PM](https://user-images.githubusercontent.com/32573897/209901284-2723b67b-86fc-4975-a6fe-d0e39186b281.png)
![Screenshot 2022-12-28 at 7 54 00 PM](https://user-images.githubusercontent.com/32573897/209901541-ebe460ca-a246-4b0a-94d6-d480515e628b.png)

**Comment by PlanetTeamSpeakk** [comment]
Only reason it'd say that is because DevLogin is not (properly) on the classpath.

**Comment by mageowl** [comment]
How do I fix this?

**Comment by PlanetTeamSpeakk** [comment]
What does your build.gradle file look like?

**Comment by PlanetTeamSpeakk** [comment]
Closed due to inactivity. If this problem still persists, feel free to open a new issue.
